### ISSUE TITLE
Failure to deploy a Go function with version 1.19

### ISSUE THREAD

**Issue by compoundinvest** [yc-actions/yc-sls-function#300]
When attempting to deploy a Go 1.19 function to Yandex Cloud Functions, the following error is returned:

```
===> executing build script
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
===> execution failed: exit status 1
```

Apparently some changes [were made to VCS file management in Go 1.18](https://github.com/golang/go/issues/37693) which likely led to this error.

Downgrading Go from 1.19 to 1.17 helped fix the issue.

Github repo: https://github.com/compoundinvest/investment-ideas
The `master` branch is using `Go 1.19` and produces the error while the `go117test` branch is using `Go 1.17` and successfully completes the GitHub action. The deployed function has been successfully tested via the Yandex Cloud Console UI.

YAML file: https://github.com/compoundinvest/investment-ideas/blob/master/.github/workflows/main.yml

**Comment by nikolaymatrosov** [comment]
Try to enumerate excluded paths explicitly:
```yaml
exclude: |
  .github/**/*
  .git/**/*
  .git
  .github
```

**Comment by compoundinvest** [comment]
@nikolaymatrosov thanks a lot, your suggestion has helped!
