### ISSUE TITLE
Добавление файлов из директории без директории

### ISSUE THREAD

**Issue by max-zorn** [yc-actions/yc-sls-function#320]
Возможно ли заливать файлы проекта, не включая путь/директорию в которой они находятся?

Например, если указываю:

`include: 
    ./src`

то в функции Яндекса будет так:

![image](https://user-images.githubusercontent.com/40857648/214460497-266e45f8-21e4-4aec-a27d-664f373ce3e8.png)

Возможно ли как-то изменить include чтобы было так:

![image](https://user-images.githubusercontent.com/40857648/214460645-a5400617-acc7-4a8f-a8f9-c2cffe90a887.png)

пробовал различные комбинации .src/*.py - не работают. По этой же причине не получается и выбрать из директории только некоторые файлы вместо того, чтобы копировать в Яндекс вообще всё, что там есть.

**Comment by nikolaymatrosov** [comment]
А зачем вам это нужно?

**Comment by max-zorn** [comment]
Мне нужно залить в разные каталоги Яндекс облака много функций, которые объединены логически, но чуть разные по функционалу, поэтому удобно их хранить в одном репозитории, но при этом в разных директориях, получается примерно такая структура:

```
-func1:
--file11.py
--file12.py
--requirements.txt
-func2:
--file21.py
--file22.py
--file23.py
--requirements.txt
-func3:
--file31.py
--requirements.txt
```

Хранить несколько репозиториев, которые по сути делают похожие вещи, но должны иметь доступ к разным ресурсам облака, наверно не очень удобно. Но так, когда я пушу отдельные директории в разные каталоги - файл зависимостей не подтягивается. Поэтому сейчас приходится хранить общий файл зависимостей и использовать функции в которых одна директория.

С этим безусловно можно жить, но было бы удобнее (если такая возможность есть), если бы можно было прокидывать в функцию собственные файлы зависимостей из своих директорий, а также, заходя в функцию видеть файлы в корне, вместо лишних директорий.

**Comment by nikolaymatrosov** [comment]
Попробуйте добавить в action новый input `source-root`. Только с ним include будет считаться от него. То есть надо будет 
```
include: ./func2
```
Поменять на 
```
source-root: ./func2
include: .
```
При этом `include: .` можно опускать, так как это дефолтное значение.
