### ISSUE TITLE
Проблема с include

### ISSUE THREAD

**Issue by D1ver** [yc-actions/yc-sls-function#367]
Возникла сложность с тем, как указывать файлы и папки в параметра include

Пример из статьи: https://medium.com/@nikolaymatrosov/github-actions-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%B8%D1%8F-cd-%D0%B2-yandex-cloud-dad32815af18

```
include: |
  ./dist
  package.json
```

В документации описано, что можно указывать и файлы, и папки. Но если я укажу 2 папки, в функцию упадет только последняя. А файлы вовсе игнорируются. Как верно указывать? И надо ли указывать source-root? Как он влияет на инклуды?

**Comment by D1ver** [comment]
у меня вот так описано

```
include: |
  ./handlers
  ./functions/myfunctionname
```

и вот эти 2 папки надо закинуть в функцию. но залетает только одна в итоге. не подкажите, что не так указываю?

и возможен ли такой вариант, когда я явно указываю файлы из конкретных папок?

```
include: |
  ./handlers/file1.py
  ./handlers/file2.py
  ./functions/myfunctionname/file3.py
  ./functions/myfunctionname/file4.py
```

**Comment by D1ver** [comment]
а, опытным путем понял, что source-root позволяет взять файлы из указанной директории, а если в конце добавить папку в инклуде, то экшен ее тоже захватит


```
source-root: './functions/functionname'
include: |
  file1.py
  requirements.txt
  ./handlers
```


но вот если вторую папку добавить в конец инклуда, то он ее проигнорирует почему-то

**Comment by nikolaymatrosov** [comment]
Попробуйте glob

**Comment by D1ver** [comment]
> Попробуйте glob

где именно его попробовать? в экшенах?

**Comment by D1ver** [comment]
Понятно: https://github.com/tj-actions/glob

**Comment by nikolaymatrosov** [comment]
Нет, просто в include.

**Comment by D1ver** [comment]
> Нет, просто в include.

да, я понял. но вот такая конструкция не работает из двух директорий:


```
include: |
  ./handlers/*
  ./functions/functionname/*
```

сохраняет только последнюю

**Comment by nikolaymatrosov** [comment]
Если не можете дать ссылку на тот репозиторий, где проблема, то подготовьте репо, где будет воспроизводиться проблема и приложите ссылку в этот issue.

**Comment by D1ver** [comment]
> Если не можете дать ссылку на тот репозиторий, где проблема, то подготовьте репо, где будет воспроизводиться проблема и приложите ссылку в этот issue.

да, он закрытый, не могу. вопрос решился примерно так:

include: |
  */functionname/functionname.py
  */functionname/requirements.txt
  */handlers/file1.py
  */handlers/file2.py
  */handlers/file3.py
  */handlers/file4.py
