### ISSUE TITLE
Перестала работать переменная source-root

### ISSUE THREAD

**Issue by D1ver** [yc-actions/yc-sls-function#429]
На последней неделе перестала работать переменная source-root.
Настройки такие:

```
          source-root: './functions/'
          include: |
            application.py
            requirements.txt
            handlers/api.py
```

Но в папку закидываются не сами файлы, а вся папка functions с этими файлами. Что изменилось?

**Comment by nikolaymatrosov** [comment]
Кажется проблема была в пустой строке. Ну по крайней мере в тестах я смог воспроизвести поведение с ней. Я добавил фильтрацию. Попробуйте новую версию

**Comment by D1ver** [comment]
> Кажется проблема была в пустой строке. Ну по крайней мере в тестах я смог воспроизвести поведение с ней. Я добавил фильтрацию. Попробуйте новую версию

Увы, без изменений.

**Comment by D1ver** [comment]
Пробовал в source-root указывать:

```
/functions/
/functions
functions
```

Тоже не срабатывает, копирует папку functions с указанными 3 файлами, хотя вообще в папке functions файлов гораздо больше.

**Comment by D1ver** [comment]
> Тогда я не понимаю что вы ожидаете

Того, как работало раньше. Я указывал сорс папку, из которой брались файлы, 3 шт. Они и ложились в функцию. А сейчас изменилась логика - в функцию стала загружаться сорс папка с 3-мя выбранными файлами.

Содержимое проекта:
```
my-app/
├── docs/
├── storage/
├── functions/
│   ├── handlers/
│   │   ├── api.py
│   │   ├── db.py
│   │   └── test.py
│   ├── application.py
│   ├── requirements.txt
│   └── database.py
```

Текущее содержимое функции:
```
├── functions/
│   ├── handlers/
│   │   └── api.py
│   ├── requirements.txt
│   └── application.py
```

Мне надо (как раньше было), чтобы в функцию закинулись только 3 файла и было следующее содержание:

```
├── handlers/
│   └── api.py
├── requirements.txt
└── application.py
```

Поэтому я указываю папку functions как исходную. Но сейчас что-то переделали и это перестало работать.

**Comment by nikolaymatrosov** [comment]
Спасибо за подробное описание. Нашел еще одну ошибку и поправил. Попробуйте снова проверить, пожалуйста.

**Comment by D1ver** [comment]
> Спасибо за подробное описание. Нашел еще одну ошибку и поправил. Попробуйте снова проверить, пожалуйста.

Да, сейчас работает отлично. Спасибо большое!
