### ISSUE TITLE
Значения чего ожидают поля bucket и folder-id?

### ISSUE THREAD

**Issue by omqmo** [yc-actions/yc-sls-function#462]
Значения чего ожидают поля bucket и folder-id?
Bucket, это имя бакета, а в качесте значения обязательного поля folder-id я должен указать имя созданной папки в этом бакете? Я правильно понимаю? Папка сама не создается?

**Comment by nikolaymatrosov** [comment]
Эти поля необходимо заполнять, только если вес архива с кодом получается более 3.5мб. Если вы пользуетесь установкой зависимостей из `package.json` во время билда, то возможно у вас архив будет меньше и его можно будет загружать напрямую без бакета.

В остальном вы правы. Папка не создается.

**Comment by omqmo** [comment]
@nikolaymatrosov на сервисном аккаунте с которого я работаю указанны роли serverless.functions.admin и storage.editor, а s3 созданбакет app-source в котором созданна папка values, но возникает ошибка - 
> Error: /yandex.cloud.serverless.functions.v1.FunctionService/Create NOT_FOUND: Folder with id values not found

В чем может быть дело? Не сталкивались с подобным?

Ну и стоит упомянуть о том, что json токен добавлен в секреты.

**Comment by nikolaymatrosov** [comment]
`folder_id` — это не про бакет. Это про облачный фолдер в котором будет создана функция.

**Comment by nikolaymatrosov** [comment]
Как указывать entrypoint зависит от того укажите ли вы `source-root`. Если укажите, то в архив будет упакована только эта директория, а значит и `entrypoint` нужно указывать от нее. Так как сервис функций, распаковав архив увидит только эту часть.

**Comment by omqmo** [comment]
@nikolaymatrosov folder_id исправил на default, но все осталось по прежднему. И у меня еще вопрос - 

> Json containing authorized key for Service Account. More info https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json

у меня в облаке не активирован container-registry, это может быть проблемой? Мне сложно понять зачем он вообще нужен... Мне нужен функционал библиотеки serverless. Этот экшен точно его повторяет? 

Сейчас посмотрел и обноружил, что у меня появился private cloud, до этого, какжется, его не было. Это экшен создал? 

Короче, это вообще не в ту сторону от того с чего начали. Прошу прощения. Мне нужно просто функцию залить из github-actions. Для меня слишком дорого сборку в облаке производить. Приложение огромное (много ГБ), и почти все генерируется в статику, обнавляется раз по пять в день. Это так в месяц сотни тысяч выйдет, когда на github можно за пуру баксов сделать.
