### ISSUE TITLE
Добавить валидацию yc-sa-json-credentials

### ISSUE THREAD

**Issue by omqmo** [yc-actions/yc-sls-function#544]
Уж не знаю, испытываю я чувство дежавю или безумия, но я снова в вашем репозитории.
В прошлый раз, при первом знакомстве с ЯО, у меня не получилось воспользоваться этим экшеном и я написал свой.
В основе использовал aws-cdk и так как на тот момент яндекс.функции не поддерживали nodejs18, то пришлось написать кучу легаси кода. Сейчас, по истечению времени у меня снова новый проект и я на распутьи - переписывать свой экшен или все-таки побидить ваш. Конечно я за второй вариант. Поэтому, перейду к сути.

```
      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SERVICE_ACCOUNT_JSON }}
          bucket: ${{ secrets.WEBSITE_DOMAIN }}.serverless
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          function-name: 'api'
          runtime: 'nodejs18'
          memory: '256Mb'
          entrypoint: 'main.handler'
          environment: |
            NODE_ENV=production
            JWT_ACCESS_SECRET=${{ secrets.AUTH_JWT_ACCESS_SECRET }}
            JWT_ACCESS_EXPIRES_IN=1h
            JWT_REFRESH_SECRET=${{ secrets.AUTH_JWT_REFRESH_SECRET }}
            JWT_REFRESH_EXPIRES_IN=1000h
            SMTP_HOST=smtp.gmail.com
            SMTP_PORT=587
            SMTP_USER=${{ secrets.SMTP_USER }}
            SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            APP_DOMAIN=${{ secrets.WEBSITE_DOMAIN }}
            APP_NAME=${{ secrets.APP_NAME }}
            APP_URL=https://${{ secrets.WEBSITE_DOMAIN }}
            APP_COMPILER_GITHUB_SECRET=${{ secrets.ACCESS_TOKEN }}
            APP_COMPILER_GITHUB_REPO=${{ secrets.APP_COMPILER_GITHUB_REPO }}
            APP_COMPILER_GITHUB_OWNER=${{ secrets.APP_COMPILER_GITHUB_OWNER }}
            APP_COMPILER_GITHUB_WORKFLOW_ID=${{ secrets.APP_COMPILER_GITHUB_WORKFLOW_ID }}
            APP_COMPILER_GITHUB_REF=${{ secrets.APP_COMPILER_GITHUB_REF }}
            CLIENT_ORIGIN=http://localhost:4200,https://${{ secrets.ADMIN_WEBSITE_DOMAIN }}
            IS_STANDALONE_ADMIN_PANEL=1
            GOOGLE_CLIENT_ID=AAA
            GOOGLE_SECRET=AAA
            GOOGLE_CALLBACK=http://localhost:3000/auth/google/redirect
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            S3_ENDPOINT_URL=https://storage.yandexcloud.net
            S3_GLOBAL_BUCKET_PREFIX=${{ secrets.WEBSITE_DOMAIN }}
            DYNAMODB_ENDPOINT_URL=${{ secrets.DYNAMODB_ENDPOINT_URL }}
          include: |
            ./src
            package.json
          exclude: |
            **/*.ts
```

YC_SERVICE_ACCOUNT_JSON выглядит вот так

```
{
  "id": "aje***",
  "service_account_id": "aje***",
  "created_at": "2023-12-05T05:34:31.998719916Z",
  "key_algorithm": "RSA_2048"
}
```

В итоге при сборке получаю 
```
Run yc-actions/yc-sls-function@v2
::add-mask::***
Function inputs set
::group::ZipDirectory
ZipDirectory
Buffer size: 2076b
::group::Find function id
Find function id
  Error: /yandex.cloud.serverless.functions.v1.FunctionService/List UNKNOWN: Getting metadata from plugin failed with error: secretOrPrivateKey must have a value
```

С чем это может быть связанно?

И вот еще что. В прошлый раз я испытывал жуткие трудности с сервисным аккаунтом и правами доступа. Я вроде создал там и сервисный аккаунт и доспут своему аккаунту дал к нему, но кто его знает получилось или нет. В прошлый раз благодаря вашей помощи получислось все запустить, но это роизошло неосознанно и поэтому сейчас проблема может быть похожей. Я даже не знаю, как это подтвердить или опровергнуть. Может есть какая-то консольная команда чтобы проверить имею я необходимые права или нет?

**Comment by omqmo** [comment]
А откуда [вот здесь](https://github.com/yc-actions/yc-sls-function/blob/9abe958ddd0f8243613a648627debaebcd3c1153/src/service-account-json.ts#L8) взялось поле `private_key`, если при генерации указанным в readme методом его нет?

**Comment by nikolaymatrosov** [comment]
Вы передаете неправильно сформированный ключ сервисного аккаунта. Тут стоило бы добавить валидацию, чтобы ошибка была более понятной.

**Comment by omqmo** [comment]
> Вы передаете неправильно сформированный ключ сервисного аккаунта. Тут стоило бы добавить валидацию, чтобы ошибка была более понятной.

Смотриет, у вас в readme указанна ссылка для генерации ключа. Я переходжу по ней и генерирую ключь с помощью команды `yc iam key create --service-account-name default-sa -o key.json`и получаю следующий вывод 
```
id: aje8a87g4e...
service_account_id: aje3932acd...
created_at: "2019-05-31T16:56:47Z"
key_algorithm: RSA_2048
```
Но вы говорите, что ключь не верный. Что я не так делаю?

**Comment by omqmo** [comment]
Пока не получислось залить функцию, но текущая ошибка пропала, так как я воспользовался генерацией ключа вот от сюда - https://cloud.yandex.ru/docs/iam/operations/sa/create-access-key

Если это правильный вариант, то может его и стоит указать в readme?

**Comment by nikolaymatrosov** [comment]
В README указана верная команда.

> Пока не получислось залить функцию, но текущая ошибка пропала, так как я воспользовался генерацией ключа вот от сюда - https://cloud.yandex.ru/docs/iam/operations/sa/create-access-key

По этой инструкции вы сгенерируете ключ не того типа.

Дальнейшее обсуждение в этом тикете считаю непродуктивным и ограничиваю возможность комментировать.
