### ISSUE TITLE
Управление триггерами из GitHubActions

### ISSUE THREAD

**Issue by pyatnitsev** [yc-actions/yc-sls-function#594]
**Is your feature request related to a problem? Please describe.**

Было бы хорошо иметь возможность создавать/редактировать trigger для Serverless.

Нужно: 

- Обновлять период запуска,
- Останавливать/запускать триггер

**Describe the solution you'd like**
Вижу как отдельный action или секция дополнительных параметров в этом воркере.
Дискуссию здесь открыть не могу как указано в репозитории, так как недостаточно прав.

**Comment by nikolaymatrosov** [comment]
https://github.com/orgs/yc-actions/discussions/1
